-- ============================================================
-- MIGRACIÓN: carga los 87 productos actuales a la tabla real
-- Pegar en Supabase → SQL Editor → Run (una sola vez)
-- ============================================================

-- Seguro de correr más de una vez: si la tabla ya tiene productos cargados, no hace nada.
do $$
begin
  if (select count(*) from productos) = 0 then
    insert into productos (nombre, categoria, tamano, precio, stock) values
      ('Shampoo Plusbelle algas exóticas', 'Limpieza e higiene', '1000ml', 3100, 10),
      ('Shampoo Plusbelle esencia', 'Limpieza e higiene', 'individual', 2400, 10),
      ('Shampoo Plusbelle esencia', 'Limpieza e higiene', 'pack x2', 3900, 10),
      ('Shampoo Sedal repuesto', 'Limpieza e higiene', null, 3900, 10),
      ('Acondicionador Sedal repuesto', 'Limpieza e higiene', null, 3100, 10),
      ('Shampoo Dove eco pack', 'Limpieza e higiene', null, 4000, 10),
      ('Shampoo/acondicionador Dove eco pack', 'Limpieza e higiene', null, 4000, 10),
      ('Detergente Cif limón bio active (chico)', 'Limpieza e higiene', null, 2200, 10),
      ('Detergente Cif limón', 'Limpieza e higiene', 'pack x2', 4500, 10),
      ('Detergente Cif limón verde', 'Limpieza e higiene', 'pack x4', 3100, 10),
      ('Papel higiénico Elegante 80 premium', 'Limpieza e higiene', 'x4', 4800, 10),
      ('Papel higiénico Elegante', 'Limpieza e higiene', 'otro pack', 2000, 10),
      ('Papel higiénico Elegante', 'Limpieza e higiene', 'otro pack', 3000, 10),
      ('Papel higiénico Felpita', 'Limpieza e higiene', 'x4', 2200, 10),
      ('Papel higiénico Campanita', 'Limpieza e higiene', 'x4', 1500, 10),
      ('Rollos de cocina New Dicha', 'Limpieza e higiene', 'x3', 1800, 10),
      ('Rollos de cocina(360 paños', 'Limpieza e higiene', 'x3', 4500, 10),
      ('Rollos de cocina Elegante', 'Limpieza e higiene', 'x3', 2300, 10),
      ('Parnor Pitusas chocolate', 'Golosinas y galletitas', null, 2000, 10),
      ('Parnor Pitusas frutilla', 'Golosinas y galletitas', null, 2000, 10),
      ('Parnor Pitusas black chocolate intenso', 'Golosinas y galletitas', null, 2000, 10),
      ('Futuro Pepas', 'Golosinas y galletitas', null, 2000, 10),
      ('Criollitas Bagley', 'Golosinas y galletitas', null, 2000, 10),
      ('Surtido Bagley', 'Golosinas y galletitas', null, 3300, 10),
      ('Bizcochitos Jorgito', 'Golosinas y galletitas', null, 2000, 10),
      ('Lia surtido galletas', 'Golosinas y galletitas', null, 2000, 10),
      ('Lia vocación galletas', 'Golosinas y galletitas', null, 2000, 10),
      ('Mediatarde clásicas', 'Golosinas y galletitas', 'pack x3', 1700, 10),
      ('Arcor diversión cookies surtido', 'Golosinas y galletitas', null, 2000, 10),
      ('Terrabusi variedad galletas', 'Golosinas y galletitas', null, 2000, 10),
      ('Don Satur salados', 'Golosinas y galletitas', null, 2000, 10),
      ('Traviatas rex/kesitas', 'Golosinas y galletitas', null, 2000, 10),
      ('Kokis membrillitos', 'Golosinas y galletitas', null, 2000, 10),
      ('Kokis cañoncitos', 'Golosinas y galletitas', null, 2000, 10),
      ('Mini coronitas black', 'Golosinas y galletitas', null, 2000, 10),
      ('Bon o Bon pasta para untar', 'Golosinas y galletitas', null, 2000, 10),
      ('Magdalenas Pozo dulce de leche', 'Golosinas y galletitas', null, 2000, 10),
      ('Pozo magdalenas con chips', 'Golosinas y galletitas', null, 2000, 10),
      ('Granix Skarchitos', 'Golosinas y galletitas', null, 2000, 10),
      ('Granix frutales (aritos)', 'Golosinas y galletitas', null, 2000, 10),
      ('Granix Baloncitos', 'Golosinas y galletitas', null, 2000, 10),
      ('Mini tapitas Fachitas', 'Golosinas y galletitas', '200g', 2000, 10),
      ('Fachitas tapitas', 'Golosinas y galletitas', null, 2000, 10),
      ('Galletitas Solitas mini alfajor', 'Golosinas y galletitas', '160g', 2000, 10),
      ('Triángulos Hojalmar', 'Golosinas y galletitas', null, 2000, 10),
      ('Fon Van Choco Van', 'Golosinas y galletitas', null, 2000, 10),
      ('For Van Vanina', 'Golosinas y galletitas', null, 2000, 10),
      ('Brunyc''s (La Fartuna)', 'Golosinas y galletitas', null, 2000, 10),
      ('Tostex avena', 'Golosinas y galletitas', null, 2000, 10),
      ('Okebon clásicas leche', 'Golosinas y galletitas', null, 2000, 10),
      ('ATB obleas rellenas', 'Golosinas y galletitas', null, 2000, 10),
      ('Cofler cookies bañadas (Arcor)', 'Golosinas y galletitas', null, 2000, 10),
      ('Mauri vainillas', 'Golosinas y galletitas', null, 2000, 10),
      ('Fantoche chispas', 'Golosinas y galletitas', null, 1200, 10),
      ('Cilo anillos sabor limón', 'Golosinas y galletitas', null, 2000, 10),
      ('Cilo pepas con baño', 'Golosinas y galletitas', null, 2200, 10),
      ('Paseo 5 semillas multicereal', 'Golosinas y galletitas', null, 1800, 10),
      ('Leiva tostaditas ciboulette', 'Snacks', null, 1700, 10),
      ('La Serenísima dulce de leche clásico', 'Almacén', '250g', 4500, 10),
      ('La Serenísima dulce de leche clásico', 'Almacén', '400g', 4500, 10),
      ('La Serenísima dulce de leche repostero', 'Almacén', null, 4500, 10),
      ('Dulce de leche aireado La Serenísima', 'Almacén', null, 4500, 10),
      ('Emeth mermelada frambuesa', 'Almacén', null, 4500, 10),
      ('Dulcor mermelada de ciruela', 'Almacén', null, 4500, 10),
      ('Miel Belén', 'Almacén', null, 4500, 10),
      ('Azúcar La Campechana', 'Almacén', '1kg', 4500, 10),
      ('Pasta Águila fondue', 'Almacén', '290g', 4500, 10),
      ('Águila Nut pasta sabor avellana', 'Almacén', null, 4500, 10),
      ('Dos Anclas cheddar', 'Almacén', '350g', 4500, 10),
      ('Dos Anclas mostaza con miel', 'Almacén', null, 4500, 10),
      ('Dos Anclas chimichurri', 'Almacén', '375g', 4500, 10),
      ('Menoyo mayonesa', 'Almacén', '235g', 4500, 10),
      ('Cañuelas mayonesa', 'Almacén', '123g', 4500, 10),
      ('Hellmann''s mayonesa', 'Almacén', '237g', 4500, 10),
      ('Hellmann''s ketchup', 'Almacén', '60g', 4500, 10),
      ('Hellmann''s ketchup', 'Almacén', '250g', 4500, 10),
      ('Savora original', 'Almacén', '40g', 4500, 10),
      ('Savora pote', 'Almacén', '200g', 4500, 10),
      ('Yerba mate Unión suave', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Aguantadora', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Taragui', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Marolio', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Playadito', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Liebig', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Mañanita', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate Salam', 'Yerba mate', '500g', 2800, 10),
      ('Yerba mate CBSE', 'Yerba mate', '550g', 2800, 10);
  end if;
end $$;
